version: '2'
services:
  db:
    image: mongo:3.0.2
    network_mode: "host"
  res-master:
    build: . 
    image: cyclomatic_complexity
    depends_on:
      - db
    extends:
      file: base.yml
      service: base 
    ports:
      - "8080:8080"
    container_name: res_master
    network_mode: "host"
    volumes:
      - /home/jibin/workspace/new_Disributed/restful-cyclomatic/results:/results
    command: python manager.py WORK_PUSHING
    
  worker1:
    image: cyclomatic_complexity 
    depends_on:
      - res-master
    ports:
      - "8083:8083"
    network_mode: "host"
    environment:
      - port=8083
    command: python worker.py
    extends:
      file: base.yml
      service: base
  worker2:
    image: cyclomatic_complexity
    depends_on:
      - res-master
    ports:
      - "8082:8082"
    network_mode: "host"
    environment:
      - port=8082
    command: python worker.py
    extends:
      file: base.yml
      service: base
  worker3:
    image: cyclomatic_complexity
    depends_on:
      - res-master
    ports:
      - "8085:8085"
    network_mode: "host"
    environment:
      - port=8085
    command: python worker.py
    extends:
      file: base.yml
      service: base
  worker4:
    image: cyclomatic_complexity
    depends_on:
      - res-master
    ports:
      - "8084:8084"
    network_mode: "host"
    environment:
      - port=8084
    command: python worker.py
    extends:
      file: base.yml
      service: base
  worker5:
    image: cyclomatic_complexity
    depends_on:
      - res-master
    ports:
      - "8086:8086"
    network_mode: "host"
    environment:
      - port=8086
    command: python worker.py
    extends:
      file: base.yml
      service: base