services:
  db:
    image: mongo:3.0.2
    network_mode: host
  res-master:
    build: .
    command: python manager.py
    container_name: res_master
    depends_on:
    - db
    environment:
    - PATTERN=MASTER_SLAVE
    - REPO=https://github.com/cpbuckingham/python.git
    image: cyclomatic_complexity
    network_mode: host
    ports:
    - 8080:8080
    volumes:
    - /home/jibin/workspace/new_Disributed/restful-cyclomatic/results:/results
  worker0:
    command: python worker.py
    depends_on:
    - res-master
    environment:
    - PATTERN=MASTER_SLAVE
    - REPO=https://github.com/cpbuckingham/python.git
    - port=8000
    image: cyclomatic_complexity
    network_mode: host
    ports:
    - 8000:8000
  # worker1:
  #   command: python worker.py
  #   depends_on:
  #   - res-master
  #   environment:
  #   - PATTERN=MASTER_SLAVE
  #   - REPO=https://github.com/cpbuckingham/python.git
  #   - port=8001
  #   image: cyclomatic_complexity
  #   network_mode: host
  #   ports:
  #   - 8001:8001
  # worker2:
  #   command: python worker.py
  #   depends_on:
  #   - res-master
  #   environment:
  #   - PATTERN=MASTER_SLAVE
  #   - REPO=https://github.com/cpbuckingham/python.git
  #   - port=8002
  #   image: cyclomatic_complexity
  #   network_mode: host
  #   ports:
  #   - 8002:8002
  # worker3:
  #   command: python worker.py
  #   depends_on:
  #   - res-master
  #   environment:
  #   - PATTERN=MASTER_SLAVE
  #   - REPO=https://github.com/cpbuckingham/python.git
  #   - port=8003
  #   image: cyclomatic_complexity
  #   network_mode: host
  #   ports:
  #   - 8003:8003
  # worker4:
  #   command: python worker.py
  #   depends_on:
  #   - res-master
  #   environment:
  #   - PATTERN=MASTER_SLAVE
  #   - REPO=https://github.com/cpbuckingham/python.git
  #   - port=8004
  #   image: cyclomatic_complexity
  #   network_mode: host
  #   ports:
  #   - 8004:8004
version: '2'
