flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- argon-0.4.1.0
- distributed-process-0.6.6
- distributed-process-simplelocalnet-0.2.3.3
- hierarchy-0.3.1
- network-multicast-0.1.2
- pipes-files-0.1.1
- posix-paths-0.2.1.0
- zip-conduit-0.2.2.2
resolver: lts-6.3
